import React, { useState, useEffect } from 'react';
import { View, Text, ScrollView, Animated } from 'react-native';

const ShowHideViewOnScroll = () => {
    const [state, setState] = useState({
        height: new Animated.Value(100),
        fadeValue: new Animated.Value(1),
        showHide: true
    })
    let offset = 0;
    const onScroll = function (event) {
        var currentOffset = event.nativeEvent.contentOffset.y;
        var direction = currentOffset > offset ? 'down' : 'up';
        if (direction === 'down') {
            setState({ ...state, showHide: false });
            Animated.timing(state.height, {
                toValue: 0,
                duration: 1000
            }).start();
            Animated.timing(state.fadeValue, {
                toValue: 0,
                duration: 500
            }).start();
        }
        else if (direction === 'up') {
            setState({ ...state, showHide: true });
            Animated.timing(state.height, {
                toValue: 100,
                duration: 1000
            }).start();
            Animated.timing(state.fadeValue, {
                toValue: 1,
                duration: 500
            }).start();
        }
        offset = currentOffset;
    }
    return (
        <View>
            {state.showHide &&
                <Animated.View style={{ height: state.height, opacity: state.fadeValue }}>
                    <Text> Show and hight </Text>
                    <Text>Show and hight </Text>
                    <Text>Show and hight </Text>
                    <Text>Show and hight </Text>
                    <Text>Show and hight </Text>
                </Animated.View>
            }
            <ScrollView onScroll={onScroll} >
                <Text>
                    Usage. Import createTransition and transition styles from the library.
                     import  from 'react-native-transition';Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                       import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                        import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                         import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                                                                              Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                  import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                         Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
            </Text>
                <Text>
                    Usage. Import createTransition and transition styles from the library.
                     import  from 'react-native-transition';Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                       import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                        import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                         import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                                                                              Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                  import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                         Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
            </Text>
                <Text>
                    Usage. Import createTransition and transition styles from the library.
                     import  from 'react-native-transition';Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                       import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                        import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                         import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                                                                              Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                  import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.                                                                                                                         Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library.
                 import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.Usage. Import createTransition and transition styles from the library. import  from 'react-native-transition'; Create a transition component with optional styles. Render the initial view within the Transition component. Use the show method from component to perform transition.
            </Text>
            </ScrollView>
        </View>
    )
}
export default ShowHideViewOnScroll;